const adventDays = [
  {
    date: 1,
    color: "Grey",
    size: "Medium",
    datePosition: "LeftBottom",
    logoPosition: "Right",
  },
  {
    date: 2,
    color: "Yellow",
    size: "Big",
    datePosition: "LeftTop",
    logoPosition: "",
  },
  {
    date: 3,
    color: "Green",
    size: "Medium",
    datePosition: "RightTop",
    logoPosition: "",
  },
  {
    date: 4,
    color: "Red",
    size: "Big",
    datePosition: "LeftBottom",
    logoPosition: "Top",
  },
  {
    date: 5,
    color: "Green",
    size: "Medium",
    datePosition: "RightBottom",
    logoPosition: "",
  },
  {
    date: 6,
    color: "Grey",
    size: "Medium",
    datePosition: "LeftTop",
    logoPosition: "Right",
  },
  {
    date: 7,
    color: "Red",
    size: "Medium",
    datePosition: "LeftTop",
    logoPosition: "",
  },
  {
    date: 8,
    color: "Orange",
    size: "Medium",
    datePosition: "RightTop",
    logoPosition: "Left",
  },
  {
    date: 9,
    color: "Yellow",
    size: "Medium",
    datePosition: "LeftTop",
    logoPosition: "Right",
  },
  {
    date: 10,
    color: "Orange",
    size: "Small",
    datePosition: "RightTop",
    logoPosition: "Bottom",
  },
  {
    date: 11,
    color: "Green",
    size: "Medium",
    datePosition: "LeftTop",
    logoPosition: "",
  },
  {
    date: 12,
    color: "Grey",
    size: "Medium",
    datePosition: "LeftTop",
    logoPosition: "",
  },
  {
    date: 13,
    color: "Green",
    size: "Medium",
    datePosition: "LeftTop",
    logoPosition: "",
  },
  {
    date: 14,
    color: "Grey",
    size: "Medium",
    datePosition: "LeftTop",
    logoPosition: "",
  },
  {
    date: 15,
    color: "Red",
    size: "Medium",
    datePosition: "LeftTop",
    logoPosition: "",
  },
  {
    date: 16,
    color: "Yellow",
    size: "Medium",
    datePosition: "LeftTop",
    logoPosition: "",
  },
  {
    date: 17,
    color: "Red",
    size: "Medium",
    datePosition: "LeftTop",
    logoPosition: "",
  },
  {
    date: 18,
    color: "Yellow",
    size: "Medium",
    datePosition: "LeftTop",
    logoPosition: "",
  },
  {
    date: 19,
    color: "Orange",
    size: "Medium",
    datePosition: "LeftTop",
    logoPosition: "",
  },
  {
    date: 20,
    color: "Green",
    size: "Medium",
    datePosition: "LeftTop",
    logoPosition: "",
  },
  {
    date: 21,
    color: "Orange",
    size: "Medium",
    datePosition: "LeftTop",
    logoPosition: "",
  },
  {
    date: 22,
    color: "Green",
    size: "Medium",
    datePosition: "LeftTop",
    logoPosition: "",
  },
  {
    date: 23,
    color: "Grey",
    size: "Medium",
    datePosition: "LeftTop",
    logoPosition: "",
  },
  {
    date: 24,
    color: "Red",
    size: "Medium",
    datePosition: "LeftTop",
    logoPosition: "",
  },
];

export default adventDays;
